[project]
name = "agentic-ai-course"
version = "0.1.0"
description = ""
authors = [
    {name = "Sharath", email = "sharath16001@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0.0"
dependencies = [
    "langchain (>=1.4.0,<2.0.0)",
    "langchain-openai (>=1.6.2,<2.0.0)",
    "langgraph (>=1.2.11,<2.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)"
]

[tool.poetry]
packages = [{include = "agentic_ai_course", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "ipykernel (>=7.3.0,<8.0.0)",
    "jupyter (>=1.1.1,<2.0.0)"
]
